#!/bin/bash


word=$(tee | awk -F '[[:space:]]+' '{ for (i=1; i<=NF; i++) if ($i != "") print $i; if ($0 != "") print $0 }' | sort | uniq | awk '{ print length, $0 }'  | sort -n | cut -d' ' -f2- | rofi -dmenu -i -p 'Copy which word?' | tr -d '\n')

if [[ -n "$word" ]]; then
    echo -n "$word" | xclip -selection clipboard
    # xdotool key --delay 0 --clearmodifiers Ctrl+Shift+v
fi
