#!/bin/sh
# Using external pipe with st, give a dmenu prompt of recent commands,
# allowing the user to copy the output of one.
# xclip required for this script.
# By Jaywalker and Luke
tmpfile=$(mktemp /tmp/st-cmd-output.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
ps1="$(strings "$tmpfile" | grep "\S" | tail -n 1 | sed 's/^\s*//' | cut -d' ' -f1)"
chosen="$(strings "$tmpfile" | grep -F "$ps1" | sed '$ d' | tac | rofi -dmenu -i -p "Copy which command's output to nvim?" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
eps1="$(echo "$ps1" | sed 's/[^^]/[&]/g; s/\^/\\^/g')"
awk "/^$chosen$/{p=1;print;next} p&&/$eps1/{p=0};p" "$tmpfile" | bash -c nvim -c 'setlocal bt=nofile bh=wipe nobl noswf'
