#!/bin/bash

tmpfile=$(mktemp /tmp/st-copysegment.XXXXXX)
trap 'rm "$tmpfile"' 0 1 15
sed -n "w $tmpfile"
prefix=$(cat "$tmpfile" | grep -a "\S" | tail -n 1 | sed 's/^\s*//' | sed -nE 's/(^[^>]+>).*/\1/p')
text=$(cat $tmpfile | sed "s/$prefix//" | sed -E 's/(took |at ).*$//' | sed -E "s/^.+$(whoami)[ ]+$(whoami)[ ]+[^ ]+\s+([^日]+日|[^:]+:[0-9]{2})[ ]+//" | sed 's/\x00//g' | awk -F '[[:space:]]+' '{ for (i=1; i<=NF; i++) { if ($i != "") print $i; } if ($0 != "") print $0 }' | sed -E 's/(^[ ]+|[ ]+$)//' | sed '/^\s*$/d' | sort | uniq | sed -E 's/(^[ ]+|[ ]+$)//' | awk '{ print length, $0 }' | sort -n | cut -d' ' -f2-)
echo -n "$text" | rofi-paste -s '\n' -p 'Copy which segment?'
