#!/bin/bash

text=$(tee | sed -E 's/^~[^>]+ >//' | sed -E 's/(took |at |ranger ).*$//' | sed 's/\x00//g' | awk -F '[[:space:]]+' '{ for (i=1; i<=NF; i++) { if ($i != "") print $i; } if ($0 != "") print $0 }' | sed -E 's/^\s+//' | sed -E 's/\s+$//' | sed '/^\s*$/d' | sort | uniq | awk '{ print length, $0 }' | sort -n | cut -d' ' -f2-)
echo -n "$text" | rofi-paste -s '\n' -p 'Copy which segment?'
